/**
 * GrowthBook Features TypeScript Typings
 *
 * NOTE: This file is auto generated by the GrowthBook CLI (https://docs.growthbook.io/tools/cli).
 * See https://docs.growthbook.io/tools/cli#generating-types for more information.
 *
 * DO NOT EDIT this file manually.
 */
export type AppFeatures = {
  'verticals-input-bar': string;
  'rel_completed_tasks_count': boolean;
  'flag-admin_freeze_tier-13032023': boolean;
  'trustpilot-widget-accept-offer': boolean;
  'trustpilot-widget-verticals': boolean;
  'platform-activity': boolean;
  'test-flag': boolean;
  'happy-test-flag': boolean;
  'ctf-experiments': string;
  'abc-feature': string;
  'ctf-test': boolean;
  'ab-test-save-15': boolean;
  'price-suggester-feature': boolean;
  'support-chatbot-17052024': boolean;
  'ab-test-insured-cleaning': boolean;
  'content-moderation-ai': boolean;
  'dinero-24062024': boolean;
  'ai-offer-suggester': boolean;
  'price-suggester-feature_2': boolean;
  'chat-bot-handyhand': boolean;
  'censoring-consecutive-messages-1410204': boolean;
  'contact_info_nudge': boolean;
  'gbdemo-checkout-layout': string;
}
